CC= g++

ALL: state flip Hconstruction blockdiaviamag momentumstates
state: state.o
	  $(CC) -o state state.o
flip: flip.o
	  $(CC) -o flip flip.o
	  
Hconstruction: Hconstruction.o
	  $(CC) -o Hconstruction Hconstruction.o
	  
blockdiaviamag: blockdiaviamag.o
	  $(CC) -o blockdiaviamag blockdiaviamag.o
	  
momentumstates: momentumstates.o
	  $(CC) -o momentumstates momentumstates.o
